version: "3.9"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]


# TODO добавить сервисы
  rabbit:
    image: rabbitmq:3.9.2-management-alpine
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq/data/:/var/lib/rabbitmq/"
      - "./rabbitmq/log/:/var/log/rabbitmq/"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_local_alarms"]

  api-gateway:
    build:
      context: ./CarRentalSystem
      dockerfile: ./APIGateway/Dockerfile
    container_name: api-gateway
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - car-service
      - rental-service
      - payment-service
      - rabbit
    healthcheck:
      test: "wget -nv -t1 --spider localhost:8080/manage/health/liveness"

  car-service:
    build:
      context: ./CarRentalSystem
      dockerfile: ./Cars/Dockerfile
    container_name: car-service
    restart: on-failure
    ports:
      - "8070:8070"
    environment:
      - PORT=8070
    depends_on:
      - postgres
    healthcheck:
      test: "wget -nv -t1 --spider localhost:8070/manage/health/liveness"

  rental-service:
    build:
      context: ./CarRentalSystem
      dockerfile: ./Rentals/Dockerfile
    container_name: rental-service
    restart: on-failure
    ports:
      - "8060:8060"
    environment:
      - PORT=8060
    depends_on:
      - postgres
    healthcheck:
      test: "wget -nv -t1 --spider localhost:8060/manage/health/liveness"

  payment-service:
    build:
      context: ./CarRentalSystem
      dockerfile: ./Payments/Dockerfile
    container_name: payment-service
    restart: on-failure
    ports:
      - "8050:8050"
    environment:
      - PORT=8050
    depends_on:
      - postgres
      - rabbit
    healthcheck:
      test: "wget -nv -t1 --spider localhost:8050/manage/health/liveness"

volumes:
  db-data: