name: GitHub Classroom Workflow
on:
  push:
    branches: [ develop ]

env:
  KUBE_HOST: ${{ secrets.KUBE_HOST }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish images
        timeout-minutes: 15
        run: |
          sudo chmod +x ./scripts/build-images.sh
          ./scripts/build-images.sh

      - name: Deploy
        run: |
          echo "run deploy"
          echo kubectl config set-cluster rsoi-cars-service-cluster --server="KUBE_HOST" --insecure-skip-tls-verify=true
          kubectl config set-cluster rsoi-cars-service-cluster --server="$KUBE_HOST" --insecure-skip-tls-verify=true
          echo kubectl config set-credentials cloud_okteto_com-user --token=KUBE_TOKEN
          kubectl config set-credentials cloud_okteto_com-user --token="$KUBE_TOKEN"
          echo kubectl config set-context default --cluster=rsoi-cars-service-cluster --user=cloud_okteto_com-user --namespace=\"platosha-git\"
          kubectl config set-context default --cluster=rsoi-cars-service-cluster --user=cloud_okteto_com-user --namespace="platosha-git"
          
          kubectl config use-context default
          echo kubectl get pods
          kubectl get pods
          cd k8s && helm delete services && helm install services ./services-chart
          sleep 45

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"